import jsPDF from 'jspdf';
import { Evaluation, Event, Participant } from '../lib/storage';

export const generateEvaluationPDF = (
  participant: Participant,
  event: Event,
  evaluation: Evaluation
) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFillColor(37, 99, 235); // Blue
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text('EVALYTICS', 105, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.text('Evaluation Report', 105, 30, { align: 'center' });
  
  // Reset text color
  doc.setTextColor(0, 0, 0);
  
  // Participant Info
  doc.setFontSize(16);
  doc.text('Participant Information', 20, 55);
  
  doc.setFontSize(11);
  doc.text(`Name: ${participant.name}`, 20, 65);
  doc.text(`Email: ${participant.email}`, 20, 72);
  if (participant.teamName) {
    doc.text(`Team: ${participant.teamName}`, 20, 79);
  }
  
  // Event Info
  doc.setFontSize(16);
  doc.text('Event Information', 20, 95);
  
  doc.setFontSize(11);
  doc.text(`Event: ${event.name}`, 20, 105);
  doc.text(`Type: ${event.type}`, 20, 112);
  doc.text(`Date: ${new Date(evaluation.submittedAt).toLocaleDateString()}`, 20, 119);
  
  // Performance Score
  doc.setFontSize(16);
  doc.text('Performance Score', 20, 135);
  
  // Performance level box
  const performanceConfig = {
    red: { label: 'Needs Improvement', color: [239, 68, 68] },
    orange: { label: 'Average', color: [249, 115, 22] },
    yellow: { label: 'Good', color: [234, 179, 8] },
    green: { label: 'Excellent', color: [34, 197, 94] }
  };
  
  const perfConfig = performanceConfig[evaluation.performanceLevel];
  doc.setFillColor(...perfConfig.color);
  doc.rect(20, 142, 170, 25, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.text(perfConfig.label, 105, 152, { align: 'center' });
  doc.setFontSize(20);
  doc.text(`${evaluation.totalScore.toFixed(1)}/100`, 105, 162, { align: 'center' });
  
  // Reset text color
  doc.setTextColor(0, 0, 0);
  
  // Category Scores
  doc.setFontSize(16);
  doc.text('Category Breakdown', 20, 182);
  
  doc.setFontSize(10);
  let yPosition = 192;
  
  Object.entries(evaluation.scores).forEach(([category, score]) => {
    if (yPosition > 270) {
      doc.addPage();
      yPosition = 20;
    }
    doc.text(`${category}:`, 20, yPosition);
    doc.text(`${score}/100`, 160, yPosition);
    yPosition += 7;
  });
  
  // Comments
  if (evaluation.comments) {
    if (yPosition > 240) {
      doc.addPage();
      yPosition = 20;
    }
    
    doc.setFontSize(16);
    doc.text('Feedback', 20, yPosition + 10);
    
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(evaluation.comments, 170);
    doc.text(lines, 20, yPosition + 20);
  }
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Generated by EVALYTICS - Page ${i} of ${pageCount}`,
      105,
      290,
      { align: 'center' }
    );
  }
  
  // Save the PDF
  doc.save(`${participant.name.replace(/\s+/g, '_')}_Evaluation_Report.pdf`);
};
